# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G -Xms4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

# The Acknowledgment Edition
the_acknowledgment_edition=20

# Mod
mod_version=2.30.2
mod_group=com.aizistral.enigmaticlegacy
mod_id=enigmaticlegacy
mod_name=Enigmatic Legacy
mod_archives_name=EnigmaticLegacy
mod_url=https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy
issue_tracker_url=https://github.com/Aizistral-Studios/Enigmatic-Legacy/issues
mod_author=Aizistral

mod_description=This mod is designed to provide tools that will aid you in exploring seemingly endless reaches of Minecraft's worlds. As well as new resources, powerful gear and ancient relics - to reward you for doing so. Despite revolving around themes of arcane and mystery, Enigmatic Legacy doesn't stray too far away from what vanilla has to offer, instead attempting to expand upon its mechanics and fill in the holes left open.

mod_credits=Terraria and some of its mods, for inspiring my creations functionally and visually; Minecraft Dungeons, for blocks and models that make me question why we don't have anything like this in Minecraft itself; Botania and it's creator known as Vazkii, for some basic code I could conveniently borrow instead of having to re-invent the wheel; frdovahkick, for amazing work over some of the textures in the mod; SkySem, for some models and textures created on-comission; SoulRacer65, for some textures overhauls and entirely new textures; Cartoony Clangs (hit with spade)_16bit.wav by Timbre -- https://freesound.org/s/91696/ -- License: Attribution NonCommercial 4.0; Shovel Thwack 1.wav by snardin42 -- https://freesound.org/s/73200/ -- License: Creative Commons 0

mod_icon=EL_logo.png
mod_license=Enigmatic Legacy License

# Dependency specifications for mods.toml
dep_forge=[47.4.0,)
dep_minecraft=[1.20,1.21)
dep_curios=[1.20.1-5.9.1,)
ver_curios=5.9.1+1.20.1
dep_patchouli=[1.20.1-84,)
ver_patchouli=1.20.1-84-FORGE
dep_caelus=[1.20.1-3.2.0,)
ver_caelus=3.2.0+1.20.1

# Dependencies specifications for build.gradle
version_mc=1.20.1
version_mc_range=[1.20.1,)
version_forge=47.4.0
version_forge_range=[47.4.0,)
version_mcp=2023.07.30-1.20.1
version_loader_range=[47,)

# CurseGradle
curse_id=336184
curse_release=release
