license="no_license"
modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/Extegral"
[[mods]]
modId="enigmaticlegacy"
version="1.0.0"
displayName="Enigmatic Legacy"
displayURL="https://www.curseforge.com/minecraft/mc-mods"
logoFile="EL_logo.png"
credits="no_credits"
description='''
Dummy mods.toml specification; required for Eclipse runs to work properly.
'''