license="WTFPL"
modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (26 is current forge version)
issueTrackerURL="https://github.com/Extegral/Enigmatic-Legacy/issues" #optional
[[mods]] #mandatory
modId="enigmaticlegacy" #mandatory
version="2.0.0" #mandatory
displayName="Enigmatic Legacy" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy" #optional
logoFile="EL_logo.png" #optional
credits="Terraria and some of it's mods, for inspiring my creations functionally and visually; frdovahkick, for amazing work over some of the textures in the mod." #optional
authors="Integral" #optional
description='''
This mod is designed to provide tools that will aid you in exploring seemingly endless reaches of Minecraft's worlds. As well as new resources, powerful gear and ancient relics - to reward you for doing so. Despite revolving around themes of arcane and mystery, Enigmatic Legacy doesn't stray too far away from what vanilla has to offer, instead attempting to expand upon it's mechanics and fill in the holes left open.
'''
[[dependencies.enigmaticlegacy]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32.0.67,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.enigmaticlegacy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enigmaticlegacy]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.16.1-3.0-beta4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.enigmaticlegacy]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.16-39,)"
    ordering="NONE"
    side="BOTH"
